In [1]:
import numpy as np
import xarray as xr
import pandas as pd

In [2]:
import sys
sys.path.append('./../Scripts')
import flux_area_integration as fai

In [3]:
import importlib as ilib
ilib.reload(fai)

<module 'flux_area_integration' from './../Scripts/flux_area_integration.py'>

In [4]:
Rayner = './../data/fco2_Rayner-C13-2018_June2018-ext3_1992-2012_monthlymean_XYT.nc'
df = xr.open_dataset(Rayner)

In [5]:
lat = df.latitude
lon = df.longitude

In [6]:
df['ocean'].sel(time=df.time[0])

<xarray.DataArray 'ocean' (latitude: 180, longitude: 360)>
array([[0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       ...,
       [1.256956, 1.256956, 1.256956, ..., 1.256956, 1.256956, 1.256956],
       [1.256957, 1.256957, 1.256957, ..., 1.256957, 1.256957, 1.256957],
       [1.256962, 1.256962, 1.256962, ..., 1.256962, 1.256962, 1.256962]],
      dtype=float32)
Coordinates:
  * longitude  (longitude) float64 -179.5 -178.5 -177.5 ... 177.5 178.5 179.5
  * latitude   (latitude) float64 -89.5 -88.5 -87.5 -86.5 ... 87.5 88.5 89.5
    time       object 1992-01-16 00:00:00
Attributes:
    title:    ocean
    units:    gC/m2/year

In [7]:
ocean = df['ocean'].sel(time=df.time[0]).values
ocean

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [1.2569561, 1.2569561, 1.2569561, ..., 1.2569561, 1.2569561,
        1.2569561],
       [1.2569572, 1.2569572, 1.2569572, ..., 1.2569572, 1.2569572,
        1.2569572],
       [1.2569623, 1.2569623, 1.2569623, ..., 1.2569623, 1.2569623,
        1.2569623]], dtype=float32)

In [8]:
eag = fai.earth_area_grid(lat, lon)
eag

array([[1.07896236e+08, 1.07896236e+08, 1.07896236e+08, ...,
        1.07896236e+08, 1.07896236e+08, 1.07896236e+08],
       [3.23655841e+08, 3.23655841e+08, 3.23655841e+08, ...,
        3.23655841e+08, 3.23655841e+08, 3.23655841e+08],
       [5.39316857e+08, 5.39316857e+08, 5.39316857e+08, ...,
        5.39316857e+08, 5.39316857e+08, 5.39316857e+08],
       ...,
       [5.39316857e+08, 5.39316857e+08, 5.39316857e+08, ...,
        5.39316857e+08, 5.39316857e+08, 5.39316857e+08],
       [3.23655841e+08, 3.23655841e+08, 3.23655841e+08, ...,
        3.23655841e+08, 3.23655841e+08, 3.23655841e+08],
       [1.07896236e+08, 1.07896236e+08, 1.07896236e+08, ...,
        1.07896236e+08, 1.07896236e+08, 1.07896236e+08]])

In [9]:
eag*ocean

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [6.77897613e+08, 6.77897613e+08, 6.77897613e+08, ...,
        6.77897613e+08, 6.77897613e+08, 6.77897613e+08],
       [4.06821530e+08, 4.06821530e+08, 4.06821530e+08, ...,
        4.06821530e+08, 4.06821530e+08, 4.06821530e+08],
       [1.35621500e+08, 1.35621500e+08, 1.35621500e+08, ...,
        1.35621500e+08, 1.35621500e+08, 1.35621500e+08]])

In [10]:
(eag*ocean)[lat>23]

array([[3.45603863e+10, 3.45603863e+10, 3.45603863e+10, ...,
        2.27681023e+09, 2.27681023e+09, 2.27681023e+09],
       [3.42928657e+10, 3.42928657e+10, 3.42928657e+10, ...,
        2.25918634e+09, 2.25918634e+09, 2.25918634e+09],
       [3.40148938e+10, 3.40148938e+10, 3.40148938e+10, ...,
        2.24087344e+09, 2.24087344e+09, 2.24087344e+09],
       ...,
       [6.77897613e+08, 6.77897613e+08, 6.77897613e+08, ...,
        6.77897613e+08, 6.77897613e+08, 6.77897613e+08],
       [4.06821530e+08, 4.06821530e+08, 4.06821530e+08, ...,
        4.06821530e+08, 4.06821530e+08, 4.06821530e+08],
       [1.35621500e+08, 1.35621500e+08, 1.35621500e+08, ...,
        1.35621500e+08, 1.35621500e+08, 1.35621500e+08]])

In [11]:
nag = fai.earth_area_grid(lat[lat>23], lon)
o = ocean[lat>23]
nag*o

array([[3.45603863e+10, 3.45603863e+10, 3.45603863e+10, ...,
        2.27681023e+09, 2.27681023e+09, 2.27681023e+09],
       [3.42928657e+10, 3.42928657e+10, 3.42928657e+10, ...,
        2.25918634e+09, 2.25918634e+09, 2.25918634e+09],
       [3.40148938e+10, 3.40148938e+10, 3.40148938e+10, ...,
        2.24087344e+09, 2.24087344e+09, 2.24087344e+09],
       ...,
       [6.77897613e+08, 6.77897613e+08, 6.77897613e+08, ...,
        6.77897613e+08, 6.77897613e+08, 6.77897613e+08],
       [4.06821530e+08, 4.06821530e+08, 4.06821530e+08, ...,
        4.06821530e+08, 4.06821530e+08, 4.06821530e+08],
       [1.35621500e+08, 1.35621500e+08, 1.35621500e+08, ...,
        1.35621500e+08, 1.35621500e+08, 1.35621500e+08]])

In [12]:
((eag*ocean)[lat>23]==nag*o)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [13]:
lat.values

array([-89.5, -88.5, -87.5, -86.5, -85.5, -84.5, -83.5, -82.5, -81.5,
       -80.5, -79.5, -78.5, -77.5, -76.5, -75.5, -74.5, -73.5, -72.5,
       -71.5, -70.5, -69.5, -68.5, -67.5, -66.5, -65.5, -64.5, -63.5,
       -62.5, -61.5, -60.5, -59.5, -58.5, -57.5, -56.5, -55.5, -54.5,
       -53.5, -52.5, -51.5, -50.5, -49.5, -48.5, -47.5, -46.5, -45.5,
       -44.5, -43.5, -42.5, -41.5, -40.5, -39.5, -38.5, -37.5, -36.5,
       -35.5, -34.5, -33.5, -32.5, -31.5, -30.5, -29.5, -28.5, -27.5,
       -26.5, -25.5, -24.5, -23.5, -22.5, -21.5, -20.5, -19.5, -18.5,
       -17.5, -16.5, -15.5, -14.5, -13.5, -12.5, -11.5, -10.5,  -9.5,
        -8.5,  -7.5,  -6.5,  -5.5,  -4.5,  -3.5,  -2.5,  -1.5,  -0.5,
         0.5,   1.5,   2.5,   3.5,   4.5,   5.5,   6.5,   7.5,   8.5,
         9.5,  10.5,  11.5,  12.5,  13.5,  14.5,  15.5,  16.5,  17.5,
        18.5,  19.5,  20.5,  21.5,  22.5,  23.5,  24.5,  25.5,  26.5,
        27.5,  28.5,  29.5,  30.5,  31.5,  32.5,  33.5,  34.5,  35.5,
        36.5,  37.5,

In [14]:
np.arange(-179.5, 180.5)==lon.values

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [20]:
spa = fai.spatial_integration(df, ['Terrestrial_flux', 'ocean'], time=(0,24))

In [21]:
fai.year_integration(spa)

Year earth_land_total south_land_total trop_land_total north_land_total  \
0  1992         -29.4476          2.69072        -9.73824         -22.4001   
1  1993         -40.4063         -4.46368        -4.55531         -31.3873   
2  1994         -1.63932         0.411662         -1.8303        -0.220681   

  earth_ocean_total south_ocean_total trop_ocean_total north_ocean_total  
0          -3.00218           6.11725         -5.81536          -3.30407  
1           14.9359           12.9816        -0.143693           2.09792  
2           1.29074          0.194098          0.29251          0.804128

In [23]:
fai.whole_time_integration(spa)

earth_land_total    -71.493203
south_land_total     -1.361304
trop_land_total     -16.123846
north_land_total    -54.008052
earth_ocean_total    13.224412
south_ocean_total    19.292977
trop_ocean_total     -5.666548
north_ocean_total    -0.402018
dtype: float64