In [1]:
import pickle
import numpy as np
import scipy
from scipy import stats
import matplotlib.pyplot as plt
import pandas as pd
import xarray as xr

/home/student.unimelb.edu.au/rursino/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)


In [11]:
def open_inversions(names):
    
    dict_of_models = {}
    for name in names:
        dict_of_models[name] = pickle.load(open(f"./../Output/output_raw/output_all/{name}_all/spatial.pik", "rb"))
    
    return dict_of_models

names = ["CAMS", "JAMSTEC", "CTRACKER", "JENA_s85", "JENA_s76", "Rayner"]
dict_invs = open_inversions(names)

In [12]:
dict_invs["CAMS"]

<xarray.Dataset>
Dimensions:         (time: 468)
Coordinates:
  * time            (time) object 1979-01-16 00:00:00 ... 2017-12-16 00:00:00
Data variables:
    Earth_Land      (time) float64 0.4314 0.5878 0.8693 ... 1.254 1.15 0.4502
    South_Land      (time) float64 0.03146 0.04228 0.06212 ... -0.03757 0.01857
    Tropical_Land   (time) float64 -0.3288 0.06462 0.4028 ... 0.2813 -0.3327
    North_Land      (time) float64 0.7288 0.4809 0.4045 ... 0.7788 0.9061 0.7644
    Earth_Ocean     (time) float64 -0.09067 -0.09578 ... -0.1494 -0.1669
    South_Ocean     (time) float64 -0.06071 -0.06981 -0.0825 ... -0.1165 -0.1023
    Tropical_Ocean  (time) float64 0.0794 0.081 0.09499 ... 0.04063 0.03863
    North_Ocean     (time) float64 -0.1094 -0.107 -0.1056 ... -0.07353 -0.1032

In [29]:
def extract_var(dict_invs, var):
    
    dict_var = {}
    for name, inv in dict_invs.items():
        dict_var[name] = inv[var]
    
    return dict_var

In [41]:
extract_var(dict_invs, "Earth_Land").values()

dict_values([<xarray.DataArray 'Earth_Land' (time: 468)>
array([0.43142 , 0.587814, 0.869325, ..., 1.254084, 1.149867, 0.450207])
Coordinates:
  * time     (time) object 1979-01-16 00:00:00 ... 2017-12-16 00:00:00, <xarray.DataArray 'Earth_Land' (time: 264)>
array([0.659963, 0.546707, 0.263685, ..., 1.411561, 1.043622, 0.386004])
Coordinates:
  * time     (time) object 1996-01-16 00:00:00 ... 2017-12-16 00:00:00, <xarray.DataArray 'Earth_Land' (time: 216)>
array([0.373699, 0.457714, 0.338313, ..., 0.880358, 0.951553, 0.942229])
Coordinates:
  * time     (time) object 2000-01-16 00:00:00 ... 2017-12-16 00:00:00, <xarray.DataArray 'Earth_Land' (time: 396)>
array([0.556644, 0.494319, 0.463078, ..., 1.121422, 1.345404, 1.013329])
Coordinates:
  * time     (time) object 1985-01-16 00:00:00 ... 2017-12-16 00:00:00, <xarray.DataArray 'Earth_Land' (time: 504)>
array([0.297948, 0.202695, 0.336327, ..., 0.952913, 1.267881, 1.004401])
Coordinates:
  * time     (time) object 1976-01-16 00:00:00 ..